name: Expenses ğŸ“
on:
  push:
    paths:
      - 'forms/**'
      - '.github/workflows/forms.yml'

jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./forms

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: flutter build web --web-renderer html --release